local _, mUI = ...

mUI.config = {}

mUI.config.anchors = {
	"CENTER",
	"TOP",
	"RIGHT",
	"BOTTOM",
	"LEFT",
	"TOPRIGHT",
	"BOTTOMRIGHT",
	"TOPLEFT",
	"BOTTOMLEFT"
}

-- Defaults
local defaultProfile = {
	settings = {
		smooth = true,
		dark = false,
		healthTexture = "Nucks",
		powerTexture = "Tim",
		castbarTexture = "Nucks",
		font = "Poppins Bold",
		borderTexture = "MangoSquare",
		borderSize = 1,
		borderOffset = 1,
		hide = {
			bags = true,
			social = true,
			menu = true
		},
		minimap = true,
		auras = true,
	},
	player = {
		enabled = true,
		anchor = "RIGHT",
		parentAnchor = "CENTER",
		width = 220,
		height = 50,
		x = -200,
		y = -210,
		power = {
			enabled = true,
			detach = false,
			reverse = false,
			offsetL = 0,
			offsetR = 0,
			offsetY = 0,
			width = 160,
			height = 10,
			x = 0,
			y = 0,
			text = {
				enabled = true,
				size = 14,
				anchor = "CENTER",
				parentAnchor = "CENTER",
				offsetX = 0,
				offsetY = 0,
			},
		},
		castbar = {
			enabled = true,
			detach = false,
			shield = false,
			icon = false,
			width = 200,
			height = 20,
			offsetY = 0,
			x = 0,
			y = 0
		},
		classpower = {
			enabled = true,
			detach = false,
			width = 200,
			height = 8,
			spacing = 4,
			x = 0,
			y = -200
		},
		portrait = {
			enabled = false,
			alpha = 0.2,
		},
		buffs = {
			enabled = true,
			blizzard = true,
			include = {},
			exclude = {},
		},
		debuffs = {
			enabled = true,
			blizzard = true,
			include = {},
			exclude = {},
		},
		prio = {
			enabled = true,
			width = 28,
			height = 28,
		},
	},
	target = {
		enabled = true,
		anchor = "LEFT",
		parentAnchor = "CENTER",
		width = 220,
		height = 50,
		x = 200,
		y = -210,
		power = {
			enabled = true,
			detach = false,
			reverse = false,
			offsetL = 0,
			offsetR = 0,
			offsetY = 0,
			width = 160,
			height = 10,
			x = 0,
			y = 0,
			text = {
				enabled = true,
				size = 14,
				anchor = "CENTER",
				parentAnchor = "CENTER",
				offsetX = 0,
				offsetY = 0,
			},
		},
		castbar = {
			enabled = true,
			detach = false,
			shield = false,
			icon = true,
			width = 200,
			height = 20,
			offsetY = 0,
			x = 0,
			y = 0
		},
		portrait = {
			enabled = false,
			alpha = 0.2,
		},
		buffs = {
			enabled = true,
			blizzard = true,
			include = {},
			exclude = {},
		},
		debuffs = {
			enabled = true,
			blizzard = true,
			include = {},
			exclude = {},
		},
	},
	pet = {
		enabled = true,
		anchor = "LEFT",
		parentAnchor = "CENTER",
		width = 110,
		height = 30,
		x = -480,
		y = -180,
		power = {
			enabled = true,
			detach = false,
			reverse = false,
			offsetL = 0,
			offsetR = 0,
			offsetY = 0,
			width = 90,
			height = 8,
			x = 0,
			y = 0,
			text = {
				enabled = true,
				size = 10,
				anchor = "CENTER",
				parentAnchor = "CENTER",
				offsetX = 0,
				offsetY = 0,
			},
		},
		castbar = {
			enabled = true,
			detach = false,
			shield = false,
			icon = true,
			width = 200,
			height = 20,
			offsetY = 0,
			x = 0,
			y = 0
		},
		portrait = {
			enabled = false,
			alpha = 0.2,
		},
	},
	targettarget = {
		enabled = true,
		anchor = "LEFT",
		parentAnchor = "CENTER",
		width = 110,
		height = 30,
		x = 480,
		y = -180,
		power = {
			enabled = true,
			detach = false,
			reverse = false,
			offsetL = 0,
			offsetR = 0,
			offsetY = 0,
			width = 90,
			height = 8,
			x = 0,
			y = 0,
			text = {
				enabled = true,
				size = 10,
				anchor = "CENTER",
				parentAnchor = "CENTER",
				offsetX = 0,
				offsetY = 0,
			},
		},
		portrait = {
			enabled = false,
			alpha = 0.2,
		},
	},
	focus = {
		enabled = true,
		anchor = "LEFT",
		parentAnchor = "CENTER",
		width = 200,
		height = 40,
		x = 20,
		y = 400,
		power = {
			enabled = true,
			detach = false,
			reverse = false,
			offsetL = 0,
			offsetR = 0,
			offsetY = 0,
			width = 200,
			height = 10,
			x = 0,
			y = 0,
			text = {
				enabled = true,
				size = 12,
				anchor = "CENTER",
				parentAnchor = "CENTER",
				offsetX = 0,
				offsetY = 0,
			},
		},
		castbar = {
			enabled = true,
			detach = false,
			shield = false,
			icon = true,
			width = 200,
			height = 20,
			offsetY = 0,
			x = 0,
			y = 0
		},
		portrait = {
			enabled = false,
			alpha = 0.2,
		},
		buffs = {
			enabled = true,
			blizzard = true,
			include = {},
			exclude = {},
		},
		debuffs = {
			enabled = true,
			blizzard = true,
			include = {},
			exclude = {},
		},
		prio = {
			enabled = true,
			width = 28,
			height = 28,
		},
	},
	boss = {
		enabled = true,
		anchor = "LEFT",
		parentAnchor = "CENTER",
		width = 180,
		height = 40,
		x = 350,
		y = -350,
		power = {
			enabled = true,
			detach = false,
			reverse = false,
			offsetL = 0,
			offsetR = 0,
			offsetY = 0,
			width = 160,
			height = 8,
			x = 0,
			y = 0,
			text = {
				enabled = true,
				size = 12,
				anchor = "CENTER",
				parentAnchor = "CENTER",
				offsetX = 0,
				offsetY = 0,
			},
		},
		castbar = {
			enabled = true,
			detach = false,
			shield = false,
			icon = true,
			width = 200,
			height = 20,
			offsetY = 0,
			x = 0,
			y = 0
		},
		portrait = {
			enabled = false,
			alpha = 0.2,
		},
		buffs = {
			enabled = true,
			blizzard = true,
			include = {},
			exclude = {},
		},
		debuffs = {
			enabled = true,
			blizzard = true,
			include = {},
			exclude = {},
		},
	},
	party = {
		enabled = true,
		anchor = "CENTER",
		parentAnchor = "CENTER",
		width = 180,
		height = 40,
		x = -600,
		y = 40,
		power = {
			enabled = true,
			detach = false,
			reverse = false,
			offsetL = 0,
			offsetR = 0,
			offsetY = 0,
			width = 120,
			height = 8,
			x = 0,
			y = 0,
			text = {
				enabled = true,
				size = 10,
				anchor = "CENTER",
				parentAnchor = "CENTER",
				offsetX = 0,
				offsetY = 0,
			},
		},
		portrait = {
			enabled = false,
			alpha = 0.2,
		},
		buffs = {
			enabled = true,
			blizzard = true,
			include = {},
			exclude = {},
		},
		debuffs = {
			enabled = true,
			blizzard = true,
			include = {},
			exclude = {},
		},
		prio = {
			enabled = true,
			width = 28,
			height = 28,
		},
	},
	raid = {
		enabled = true,
		anchor = "TOPLEFT",
		parentAnchor = "CENTER",
		width = 70,
		height = 50,
		x = 0,
		y = 0,
		power = {
			enabled = true,
			detach = false,
			reverse = false,
			offsetL = 0,
			offsetR = 0,
			offsetY = 0,
			width = 160,
			height = 10,
			x = 0,
			y = 0,
			text = {
				enabled = true,
				size = 10,
				anchor = "CENTER",
				parentAnchor = "CENTER",
				offsetX = 0,
				offsetY = 0,
			},
		},
		portrait = {
			enabled = true,
			alpha = 0.2,
		},
		buffs = {
			enabled = true,
			blizzard = true,
			include = {},
			exclude = {},
		},
		debuffs = {
			enabled = true,
			blizzard = true,
			include = {},
			exclude = {},
		},
		prio = {
			enabled = true,
			width = 28,
			height = 28,
		},
	},
	prio = {
		default = true,
		include = {},
		exclude = {},
	},
	totems = {
		enabled = true,
		anchor = "CENTER",
		parentAnchor = "CENTER",
		width = 32,
		height = 32,
		x = 0,
		y = 0,
	},
}

mUI.defaults = {
	MangoCharacters = {},
	MangoProfiles = {
		["default"] = defaultProfile,
	},
}
